### ISSUE TITLE
Getting errors while running rosetta_ddg_aggregate

### ISSUE THREAD

**Issue by yashrajk** [ELELAB/RosettaDDGPrediction#62] opened 2023-10-10 08:33 UTC
Hello.

I am trying to use RosettaDDGPrediction in my current project to perform saturation mutagenesis scans of peptide ligands. I am writing to request some technical assistance (Python related) that I need while running the rosetta_ddg_aggregate code.

I am currently using my local machine (MacBook Pro with the M1 chip). Python version 3.9.7. 

I have installed the package inside a virtual environment. I have followed the User Guide document available on the Github page. I am encountering error(s) despite the rosetta_ddg_run and rosetta_ddg_check_run codes running smoothly. When I run the rosetta_ddg_aggregate code, it crashes and gives out error messages that I am not able to fix (due to my not so good grounding in Python). If I include the --mutatex-convert option, I get another error.

The attached file has the error output from two separate runs, without and with the --mutatex-convert option.

Thanks in advance!

Best,
Yash
[ddg_aggregate_errorlog.txt](https://github.com/ELELAB/RosettaDDGPrediction/files/12854703/ddg_aggregate_errorlog.txt)

**Comment by elenapapaleo** [comment] 2023-10-19 15:40
Hi! sorry for the late reply. I think we need some more info to guide you. 
You said that the  rosetta_ddg_run  worked well but could you tell us which protocol and config are you using (i.e. cartesian or flexddg)? Do you get a corresponding folder with results at the end of the run and does it contain the folders for each mutations and expected outputs? the rosetta_ddg_check_run  will do some crude quality control but in our experience there are other possible sources of issue.

**Comment by yashrajk** [comment] 2023-10-20 13:08
Hi. Thanks for your response. 

I am using the flexddg protocol, and the flexddg_ref2015.yaml config file. I have used mpirun.yaml to run parallel jobs.

I get a corresponding folder "flexddg" that contains folders for each mutations. I am attaching a screenshot of the contents of one of the 35 folders.

Please let me know if you need further information.

Thanks,
Yash
<img width="1559" alt="Screenshot 2023-10-20 at 15 08 39" src="https://github.com/ELELAB/RosettaDDGPrediction/assets/16085226/58754786-2dd2-48d8-9bc7-07b3983e573c">

**Comment by mtiberti** [comment] 2023-10-20 14:39
hi @yashrajk , from a cursory look, seems like the directories are fine. Unfortunately diagnosing your issue without access to your run and the command you're using is a bit difficult. Would you mind sharing them with us if possible? You can use a file-sharing service or feel free to drop us an [email](https://www.cancer.dk/research/dci-research/cancer-structural-biology/staff-members/) (I'm the staff scientist in the page)

**Comment by yashrajk** [comment] 2023-10-25 09:04
Hi @mtiberti . Thank you. I will share the files on email.

**Comment by sajad-stack** [comment] 2023-11-16 20:39
Hello,
I am also having a similar problem in the data aggregation step.
My command is as follows. Could you give me a clue as to what the issue might be?
Thank you


Rosetta) (base) sajad@sajad-desktop:~/Downloads/TEST/G13$ /home/sajad/Downloads/RosettaDDGPrediction-master/Rosetta/bin/rosetta_ddg_aggregate -cr /home/sajad/Downloads/RosettaDDGPrediction-master/build/lib/RosettaDDGPrediction/config_run/flexddg_ref2015.yaml -cs /home/sajad/Downloads/RosettaDDGPrediction-master/RosettaDDGPrediction/config_settings/nompi.yaml -ca /home/sajad/Downloads/RosettaDDGPrediction-master/build/lib/RosettaDDGPrediction/config_aggregate/aggregate.yaml -mf /home/sajad/Downloads/TEST/G13/flexddg/mutinfo.txt -d /home/sajad/Downloads/TEST/G13/
2023-11-16 15:33:34,242 - distributed.worker - WARNING - Compute Failed
Key:       generate_output_dataframes-b51d4f7b9ab7392334b187e32da524f1
Function:  generate_output_dataframes
args:      ()
kwargs:    {'dg_wt':        fa_atr    fa_rep     fa_sol  fa_intra_rep  fa_intra_sol_xover4  ...  rama_prepro  total_score  state  score_function_name  struct_num
0  -44.779753  3.714087  27.647823 -2.664535e-15         1.421085e-14  ...          0.0   -44.769547     wt              ref2015           1
1  -41.160378  3.686893  24.463528 -7.993606e-15         8.526513e-14  ...          0.0   -40.954163     wt              ref2015           2
2  -40.106635  3.910832  25.250559 -3.552714e-15        -1.421085e-14  ...          0.0   -40.169020     wt              ref2015           3
3  -38.908435  2.834053  19.188526 -1.509903e-14         1.136868e-13  ...          0.0   -41.521221     wt              ref2015           4
4  -39.691973  3.396158  20.130845 -1.598721e-14         0.000000e+00  ...          0.0   -37.833114     wt              ref2015           5
5  -42.329352  3.667734  23.975213  3.552714e-15         1.421085e-14  ...          0.0   -40.793321     wt              ref2015           6
6  
Exception: "TypeError('agg function failed [how->mean,dtype->object]')"

ERROR:root:Could not generate output dataframes: agg function failed [how->mean,dtype->object]
Could not generate output dataframes: agg function failed [how->mean,dtype->object]

**Comment by alexandrefassio** [comment] 2023-11-29 16:06
Hi there,

I was having the same issue. After debugging the code for a while I was able to fix this issue by editing the file **aggregation.py**. 

Basically, the error has been caused by the column **struct_df['struct_num']**, whose values are being parsed as strings (*object* type). To fix it, I converted its type to *int64* as shown below:

`struct_df[struct_num_col] = struct_df[struct_num_col].astype('int64')`

Hope this helps.
bests

**Comment by sajad-stack** [comment] 2023-11-29 23:59
Hi Alexandre,

Could you please clarify a bit more and let me know on which line of the "aggregation.py" you applied the modification?

Thank you,

**Comment by mtiberti** [comment] 2023-11-30 08:09
thank you @alexandrefassio ! If you can, would you mind submitting your code changes in a branch and opening a PR to contribute to the codebase with your change?

And another suggestion, can you print what data generate this problem (e.g. the function input)? It is a bit weird that we need to force type on a column that should contain only numbers, and apparently only in some cases, so I was wondering if there is e.g. some problem in the input of that function that we need to fix upstream

**Comment by alexandrefassio** [comment] 2023-12-19 14:53
Hi @sajad-stack and @mtiberti 

I've forked and opened a PR with the updates, which can be seen [here](https://github.com/alexandrefassio/RosettaDDGPrediction/commit/e01b7028adaee3449c602c873f40b591505349ad).

Regarding the data that generated the problem, I won't be able to share it due to research reasons. But I'll try to reproduce the error with a public protein structure and mutation.  As soon as I find something, I'll send it to you @mtiberti.

**Comment by mtiberti** [comment] 2024-01-02 09:54
@alexandrefassio amazing, thank you very much!

Sorry for the delay, I'm just back from holidays.

if you manage to find a way to easily reproduce the problem that would be fantastic, but either way thank you very much for taking the time to open a PR from your fork.

Being able to reproduce it would be best because it would allow us to investigate why that column is sometimes parsed as a string - e.g. do we get some values that should not be there for some reason?

**Comment by mtiberti** [comment] 2024-02-02 14:19
fixed in #64 - we couldn't reproduce the issue - we trust the proposed fix fixes it

**Closed by mtiberti** 2024-02-02 14:19 UTC
